public class DotClass {
    Decimal XCoordinate;
    Decimal YCoordinate;
    public DotClass(){
        XCoordinate = 3;
        YCoordinate = 5;
    }
    public DotClass(Decimal X, Decimal Y){
        XCoordinate = X;
        YCoordinate = Y;
    }
    public void inputValues (Decimal X, Decimal Y) {
        XCoordinate = X;
        YCoordinate = Y;
    } 
    public void findingDot(){
        decimal findDot;
  }
    Public void getValues(){
    system.debug('X Coordinate of Dot is ' + XCoordinate);
    system.debug('Y Cordinate of Dot is ' + YCoordinate);
    }
    
    
}